(testsuite "AST tests" (lambda ()
; these tests represent the ast tests from test.c
(let ((l (ast-list (vector))))
    (assert (= (l 'size) 0))
    (l 'eval))

(let ((l (ast-list (vector 1 2 3 4))))
    (assert (= (l 'size) 4))
    (let loop ((idx 0))
        (assert (= (l 'objectAt: idx) (+ idx 1)))
        (if (< idx (- (l 'size) 1))
            (loop (+ idx 1))
            (begin))))

(let* ((number 42)
       (const (ast-const number)))
    (assert (= (const 'eval) number)))

(let* ((number 42)
       (const (ast-const number))
       (l (ast-list (vector const))))
    (assert (= (l 'eval) number)))

(let* ((e1k "env1 identifier")
       (e2k "env2 indetifier")
       (v1 "v1")
       (v2 "v2")
       (v3 "v3")
       (env1 (Env 'scopeId:size: e1k 1))
       (env2 (Env 'scopeId:size: e2k 1)))
    (env1 'parent: null)
    (env2 'parent: env1)
    (env1 'store:at:in: v1 0 e1k)
    (assert (eq? (env1 'objectAt: 0) v1))
    )
))
