(testsuite "Symbol test" (lambda ()
    (assert ('a '= "a"))
))

(testsuite "SymbolTable test" (lambda ()
 (let ((s (SymbolTable 'basicNew)))
    (s 'symbols: (Array 'basicNew: 1))
    ((s 'symbols) 'objectAt:put: 0 'silvio)
    (s 'expand)
    (assert (= ((s 'symbols) 'size) 2))
    (assert (eq? ((s 'symbols) 'objectAt: 0) 'silvio))
    (assert (eq? (s 'intern: 'silvio) 'silvio))
    (assert (eq? ((s 'symbols) 'objectAt: 1) null))
    (assert (eq? (s 'intern: 'nicolas) 'nicolas))
    (assert (eq? (s 'intern: 'vladimir) 'vladimir))
    (assert (eq? (s 'intern: "vladimir") 'vladimir))
    (assert (= ((s 'symbols) 'size) 4))
    (assert (eq? (s 'lookup: "nicolas") 'nicolas))
    (assert (eq? (s 'lookup: 'angela) null))
    )
))
