#ifndef PINOCCHIO_LIB_SMALLTALK_PARSER_PPARSERBENCHMARK
#define PINOCCHIO_LIB_SMALLTALK_PARSER_PPARSERBENCHMARK 

#include <pinocchio.h>
extern void init_Smalltalk_Parser_PParserBenchmark_methods();

extern void init_Smalltalk_Parser_PParserBenchmark_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_Parser_ParserBenchmark_Class_class;
extern Optr slot_Smalltalk_Parser_ParserBenchmark_methodParser;
extern Optr slot_Smalltalk_Parser_ParserBenchmark_parser;
extern Optr layout_Smalltalk_Parser_ParserBenchmark;


#endif //PINOCCHIO_LIB_SMALLTALK_PARSER_PPARSERBENCHMARK