#ifndef PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKGRAMMAR
#define PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKGRAMMAR 

#include <pinocchio.h>
extern void init_Smalltalk_Parser_PSmalltalkGrammar_methods();

extern void init_Smalltalk_Parser_PSmalltalkGrammar_layout();

#include <lib/lib.h>

extern Optr slot_Smalltalk_Parser_SmalltalkGrammar_Class_class_instance;
extern Optr layout_Smalltalk_Parser_SmalltalkGrammar_Class_class;
extern Optr layout_Smalltalk_Parser_SmalltalkGrammar;


#endif //PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKGRAMMAR