#ifndef PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKPARSERTEST
#define PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKPARSERTEST 

#include <pinocchio.h>
extern void init_Smalltalk_Parser_PSmalltalkParserTest_methods();

extern void init_Smalltalk_Parser_PSmalltalkParserTest_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_Parser_SmalltalkParserTest_Class_class;
extern Optr slot_Smalltalk_Parser_SmalltalkParserTest_pparser;
extern Optr layout_Smalltalk_Parser_SmalltalkParserTest;


#endif //PINOCCHIO_LIB_SMALLTALK_PARSER_PSMALLTALKPARSERTEST