#!/bin/bash

set -e

export CFLAGS="${CFLAGS} -D_XOPEN_SOURCE"

wget http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.1.tar.gz -O boehm.tar.gz
tar xzf boehm.tar.gz

cd gc-7.1
./configure --disable-threads
make
sudo make install
