#!/usr/bin/env ruby

SMB_init = "src/system/type/SymbolInitialization.ci"


def print_symbol_definition(path)
    puts 'symbolDefintion'
    puts '    <preventExport>'
    puts '    "Auto generated Symbol definition from system/type/SymbolInitialization.ci'
    puts '     Use the script at _meta/extractSymbols to generate this method"'
    puts
    puts '    ^ #('
    File.read(path).each {|l|
        if /(SMB_.*?)\s+= new_Type_Symbol_cached\(L"(.*?)"\);/ =~ l
            puts "        ('#{$2}' '#{$1}')"
        end
    }
    puts '    )'

end

if $0 == __FILE__
    path = File.dirname($0) + '/../' + SMB_init
    print_symbol_definition(path)
end

