#ifndef PINOCCHIO_LIB_COLLECTIONS_SEQUENCEABLE_ORDEREDCOLLECTION
#define PINOCCHIO_LIB_COLLECTIONS_SEQUENCEABLE_ORDEREDCOLLECTION 

#include <pinocchio.h>
extern void init_Collections_Sequenceable_OrderedCollection_methods();

extern void init_Collections_Sequenceable_OrderedCollection_layout();

#include <lib/lib.h>

extern Optr layout_Collections_Sequenceable_OrderedCollection_Class_class;
extern Optr slot_Collections_Sequenceable_OrderedCollection_array;
extern Optr slot_Collections_Sequenceable_OrderedCollection_firstIndex;
extern Optr slot_Collections_Sequenceable_OrderedCollection_lastIndex;
extern Optr layout_Collections_Sequenceable_OrderedCollection;


#endif //PINOCCHIO_LIB_COLLECTIONS_SEQUENCEABLE_ORDEREDCOLLECTION