#ifndef PINOCCHIO_LIB_KERNEL_EXCEPTION_PRECURSIVEDOESNOTUNDERSTAND
#define PINOCCHIO_LIB_KERNEL_EXCEPTION_PRECURSIVEDOESNOTUNDERSTAND 

#include <pinocchio.h>
extern void init_Kernel_Exception_PRecursiveDoesNotUnderstand_methods();

extern void init_Kernel_Exception_PRecursiveDoesNotUnderstand_layout();

#include <lib/lib.h>

extern Optr layout_Kernel_Exception_RecursiveDoesNotUnderstand_Class_class;
extern Optr layout_Kernel_Exception_RecursiveDoesNotUnderstand;


#endif //PINOCCHIO_LIB_KERNEL_EXCEPTION_PRECURSIVEDOESNOTUNDERSTAND