#ifndef PINOCCHIO_LIB_SMALLTALK_AST_ASTBINARYEXPRESSION
#define PINOCCHIO_LIB_SMALLTALK_AST_ASTBINARYEXPRESSION 

#include <pinocchio.h>
extern void init_Smalltalk_AST_ASTBinaryExpression_methods();

extern void init_Smalltalk_AST_ASTBinaryExpression_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_AST_BinaryExpression_Class_class;
extern Optr slot_Smalltalk_AST_BinaryExpression_receiver;
extern Optr slot_Smalltalk_AST_BinaryExpression_argument;
extern Optr slot_Smalltalk_AST_BinaryExpression_scoped;
extern Optr layout_Smalltalk_AST_BinaryExpression;


#endif //PINOCCHIO_LIB_SMALLTALK_AST_ASTBINARYEXPRESSION