#ifndef PINOCCHIO_LIB_SMALLTALK_AST_ASTKEYWORDMESSAGEDEFINITION
#define PINOCCHIO_LIB_SMALLTALK_AST_ASTKEYWORDMESSAGEDEFINITION 

#include <pinocchio.h>
extern void init_Smalltalk_AST_ASTKeywordMessageDefinition_methods();

extern void init_Smalltalk_AST_ASTKeywordMessageDefinition_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_AST_KeywordMessageDefinition_Class_class;
extern Optr slot_Smalltalk_AST_KeywordMessageDefinition_parameters;
extern Optr layout_Smalltalk_AST_KeywordMessageDefinition;


#endif //PINOCCHIO_LIB_SMALLTALK_AST_ASTKEYWORDMESSAGEDEFINITION