#ifndef PINOCCHIO_LIB_ORGANIZATION_PPATHSEGMENTEXCEPTION
#define PINOCCHIO_LIB_ORGANIZATION_PPATHSEGMENTEXCEPTION 

#include <pinocchio.h>
extern void init_Organization_PPathSegmentException_methods();

extern void init_Organization_PPathSegmentException_layout();

#include <lib/lib.h>

extern Optr layout_Organization_PathSegmentException_Class_class;
extern Optr slot_Organization_PathSegmentException_path;
extern Optr slot_Organization_PathSegmentException_index;
extern Optr layout_Organization_PathSegmentException;


#endif //PINOCCHIO_LIB_ORGANIZATION_PPATHSEGMENTEXCEPTION