#ifndef PINOCCHIO_LIB_ORGANIZATION_PUNDEFINEDCLASSREFERENCE
#define PINOCCHIO_LIB_ORGANIZATION_PUNDEFINEDCLASSREFERENCE 

#include <pinocchio.h>
extern void init_Organization_PUndefinedClassReference_methods();

extern void init_Organization_PUndefinedClassReference_layout();

#include <lib/lib.h>

extern Optr layout_Organization_UndefinedClassReference_Class_class;
extern Optr slot_Organization_UndefinedClassReference_reference;
extern Optr layout_Organization_UndefinedClassReference;


#endif //PINOCCHIO_LIB_ORGANIZATION_PUNDEFINEDCLASSREFERENCE