#ifndef PINOCCHIO_LIB_SMALLTALK_COMPILER_PCOMPILER
#define PINOCCHIO_LIB_SMALLTALK_COMPILER_PCOMPILER 

#include <pinocchio.h>
extern void init_Smalltalk_Compiler_PCompiler_methods();

extern void init_Smalltalk_Compiler_PCompiler_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_Compiler_Compiler_Class_class;
extern Optr slot_Smalltalk_Compiler_Compiler_scope;
extern Optr slot_Smalltalk_Compiler_Compiler_rootScope;
extern Optr slot_Smalltalk_Compiler_Compiler_world;
extern Optr slot_Smalltalk_Compiler_Compiler_pinocchioClass;
extern Optr slot_Smalltalk_Compiler_Compiler_currentMethod;
extern Optr slot_Smalltalk_Compiler_Compiler_currentBlock;
extern Optr slot_Smalltalk_Compiler_Compiler_currentCallecVariable;
extern Optr slot_Smalltalk_Compiler_Compiler_threadedCompiler;
extern Optr layout_Smalltalk_Compiler_Compiler;


#endif //PINOCCHIO_LIB_SMALLTALK_COMPILER_PCOMPILER