#ifndef PINOCCHIO_LIB_SMALLTALK_COMPILER_PUNDEFINEDVARIABLE
#define PINOCCHIO_LIB_SMALLTALK_COMPILER_PUNDEFINEDVARIABLE 

#include <pinocchio.h>
extern void init_Smalltalk_Compiler_PUndefinedVariable_methods();

extern void init_Smalltalk_Compiler_PUndefinedVariable_layout();

#include <lib/lib.h>

extern Optr layout_Smalltalk_Compiler_UndefinedVariable_Class_class;
extern Optr slot_Smalltalk_Compiler_UndefinedVariable_variable;
extern Optr layout_Smalltalk_Compiler_UndefinedVariable;


#endif //PINOCCHIO_LIB_SMALLTALK_COMPILER_PUNDEFINEDVARIABLE