#ifndef PINOCCHIO_LIB_COLLECTIONS_ABSTRACT_SEQUENCEABLECOLLECTION
#define PINOCCHIO_LIB_COLLECTIONS_ABSTRACT_SEQUENCEABLECOLLECTION 

#include <pinocchio.h>
extern void init_Collections_Abstract_SequenceableCollection_methods();

extern void init_Collections_Abstract_SequenceableCollection_layout();

#include <lib/lib.h>

extern Optr layout_Collections_Abstract_SequenceableCollection_Class_class;


#endif //PINOCCHIO_LIB_COLLECTIONS_ABSTRACT_SEQUENCEABLECOLLECTION