#ifndef PINOCCHIO_LIB_IO_TERM_PVTERMOUTPUTDRIVER
#define PINOCCHIO_LIB_IO_TERM_PVTERMOUTPUTDRIVER 

#include <pinocchio.h>
extern void init_IO_Term_PVTermOutputDriver_methods();

extern void init_IO_Term_PVTermOutputDriver_layout();

#include <lib/lib.h>

extern Optr slot_IO_Term_TermOutputDriver_Class_class_stdoutTerminalInstance;
extern Optr slot_IO_Term_TermOutputDriver_Class_class_stderrTerminalInstance;
extern Optr layout_IO_Term_TermOutputDriver_Class_class;
extern Optr slot_IO_Term_TermOutputDriver_termcap;
extern Optr slot_IO_Term_TermOutputDriver_outStream;
extern Optr slot_IO_Term_TermOutputDriver_currentBackground;
extern Optr slot_IO_Term_TermOutputDriver_currentColor;
extern Optr slot_IO_Term_TermOutputDriver_light;
extern Optr slot_IO_Term_TermOutputDriver_blink;
extern Optr slot_IO_Term_TermOutputDriver_shouldEcho;
extern Optr layout_IO_Term_TermOutputDriver;


#endif //PINOCCHIO_LIB_IO_TERM_PVTERMOUTPUTDRIVER