#ifndef PINOCCHIO_LIB_BRIDGE_TEST_SUPERCLASSTESTCLASS
#define PINOCCHIO_LIB_BRIDGE_TEST_SUPERCLASSTESTCLASS 

#include <pinocchio.h>
extern void init_Bridge_Test_SuperClassTestClass_methods();

extern void init_Bridge_Test_SuperClassTestClass_layout();

#include <lib/lib.h>

extern Optr slot_Bridge_Test_SuperClassTestClass_Class_class_a;
extern Optr slot_Bridge_Test_SuperClassTestClass_Class_class_b;
extern Optr layout_Bridge_Test_SuperClassTestClass_Class_class;
extern Optr slot_Bridge_Test_SuperClassTestClass_a;
extern Optr layout_Bridge_Test_SuperClassTestClass;


#endif //PINOCCHIO_LIB_BRIDGE_TEST_SUPERCLASSTESTCLASS