#!/usr/bin/env ruby

def run
    system("cd "+ARGV[0]+";     make run > /dev/null")
end

# first run
run()

# average runs

$runTimes = []
start = Time.now
100.times { |i|
    run()
}
puts (Time.now - start) / 100
