#ifndef PINOCCHIO_LIB_INTERPRETATION_PPARALLELDEBUGGER
#define PINOCCHIO_LIB_INTERPRETATION_PPARALLELDEBUGGER 

#include <pinocchio.h>
extern void init_Interpretation_PParallelDebugger_methods();

extern void init_Interpretation_PParallelDebugger_layout();

#include <lib/lib.h>

extern Optr layout_Interpretation_ParallelDebugger_Class_class;
extern Optr slot_Interpretation_ParallelDebugger_localIndent;
extern Optr slot_Interpretation_ParallelDebugger_threads;
extern Optr slot_Interpretation_ParallelDebugger_states;
extern Optr layout_Interpretation_ParallelDebugger;


#endif //PINOCCHIO_LIB_INTERPRETATION_PPARALLELDEBUGGER