extern void h();
extern void help();
extern void inspect(FILE* stream, Optr o);
extern void _indent_(FILE* stream,uns_int i);
extern void i(Optr o);
extern void sends();
extern void exps();
extern void nexps(int size);
extern Optr atn(Optr o, const wchar_t * s);
extern Optr at(Optr o, uns_int i);
extern Optr atx(Optr o, uns_int argc, ...);
extern void inspect_at(Optr o, uns_int i);
extern void i_at(Optr o, uns_int i);
extern void i_atn(Optr o, const wchar_t * s);
extern void inspect_atn(Optr o, const wchar_t * s);
extern Optr methods(Optr o);
