/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define PINOCCHIO_STABILITY "___dtrace_stability$pinocchio$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define PINOCCHIO_TYPEDEFS "___dtrace_typedefs$pinocchio$v2"

#define	PINOCCHIO_CHARACTER_CACHEHIT(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$character__cachehit$v1$63686172(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_CHARACTER_CACHEHIT_ENABLED() \
	__dtrace_isenabled$pinocchio$character__cachehit$v1()
#define	PINOCCHIO_CHARACTER_CACHEMISS(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$character__cachemiss$v1$63686172(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_CHARACTER_CACHEMISS_ENABLED() \
	__dtrace_isenabled$pinocchio$character__cachemiss$v1()
#define	PINOCCHIO_CHARACTER_NEW(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$character__new$v1$63686172(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_CHARACTER_NEW_ENABLED() \
	__dtrace_isenabled$pinocchio$character__new$v1()
#define	PINOCCHIO_MESSAGE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_ENABLED() \
	__dtrace_isenabled$pinocchio$message$v1()
#define	PINOCCHIO_MESSAGE_CACHEHIT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message__cachehit$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_CACHEHIT_ENABLED() \
	__dtrace_isenabled$pinocchio$message__cachehit$v1()
#define	PINOCCHIO_MESSAGE_CACHEMISS(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message__cachemiss$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_CACHEMISS_ENABLED() \
	__dtrace_isenabled$pinocchio$message__cachemiss$v1()
#define	PINOCCHIO_NEW_STRING(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$new_string$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_NEW_STRING_ENABLED() \
	__dtrace_isenabled$pinocchio$new_string$v1()
#define	PINOCCHIO_OPCODE(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$opcode$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_OPCODE_ENABLED() \
	__dtrace_isenabled$pinocchio$opcode$v1()
#define	PINOCCHIO_SMALLINT_CACHEHIT(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$smallint__cachehit$v1$6c6f6e67(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_SMALLINT_CACHEHIT_ENABLED() \
	__dtrace_isenabled$pinocchio$smallint__cachehit$v1()
#define	PINOCCHIO_SMALLINT_CACHEMISS(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$smallint__cachemiss$v1$6c6f6e67(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_SMALLINT_CACHEMISS_ENABLED() \
	__dtrace_isenabled$pinocchio$smallint__cachemiss$v1()
#define	PINOCCHIO_SMALLINT_NEW(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$smallint__new$v1$6c6f6e67(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_SMALLINT_NEW_ENABLED() \
	__dtrace_isenabled$pinocchio$smallint__new$v1()


extern void __dtrace_probe$pinocchio$character__cachehit$v1$63686172(char);
extern int __dtrace_isenabled$pinocchio$character__cachehit$v1(void);
extern void __dtrace_probe$pinocchio$character__cachemiss$v1$63686172(char);
extern int __dtrace_isenabled$pinocchio$character__cachemiss$v1(void);
extern void __dtrace_probe$pinocchio$character__new$v1$63686172(char);
extern int __dtrace_isenabled$pinocchio$character__new$v1(void);
extern void __dtrace_probe$pinocchio$message$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message$v1(void);
extern void __dtrace_probe$pinocchio$message__cachehit$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message__cachehit$v1(void);
extern void __dtrace_probe$pinocchio$message__cachemiss$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message__cachemiss$v1(void);
extern void __dtrace_probe$pinocchio$new_string$v1$63686172202a(char *);
extern int __dtrace_isenabled$pinocchio$new_string$v1(void);
extern void __dtrace_probe$pinocchio$opcode$v1$63686172202a(char *);
extern int __dtrace_isenabled$pinocchio$opcode$v1(void);
extern void __dtrace_probe$pinocchio$smallint__cachehit$v1$6c6f6e67(long);
extern int __dtrace_isenabled$pinocchio$smallint__cachehit$v1(void);
extern void __dtrace_probe$pinocchio$smallint__cachemiss$v1$6c6f6e67(long);
extern int __dtrace_isenabled$pinocchio$smallint__cachemiss$v1(void);
extern void __dtrace_probe$pinocchio$smallint__new$v1$6c6f6e67(long);
extern int __dtrace_isenabled$pinocchio$smallint__new$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
