/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define PINOCCHIO_STABILITY "___dtrace_stability$pinocchio$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define PINOCCHIO_TYPEDEFS "___dtrace_typedefs$pinocchio$v2"

#define	PINOCCHIO_MESSAGE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_ENABLED() \
	__dtrace_isenabled$pinocchio$message$v1()
#define	PINOCCHIO_MESSAGE_CACHEHIT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message__cachehit$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_CACHEHIT_ENABLED() \
	__dtrace_isenabled$pinocchio$message__cachehit$v1()
#define	PINOCCHIO_MESSAGE_CACHEMISS(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$message__cachemiss$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_MESSAGE_CACHEMISS_ENABLED() \
	__dtrace_isenabled$pinocchio$message__cachemiss$v1()
#define	PINOCCHIO_THREADED(arg0) \
do { \
	__asm__ volatile(".reference " PINOCCHIO_TYPEDEFS); \
	__dtrace_probe$pinocchio$threaded$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " PINOCCHIO_STABILITY); \
} while (0)
#define	PINOCCHIO_THREADED_ENABLED() \
	__dtrace_isenabled$pinocchio$threaded$v1()


extern void __dtrace_probe$pinocchio$message$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message$v1(void);
extern void __dtrace_probe$pinocchio$message__cachehit$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message__cachehit$v1(void);
extern void __dtrace_probe$pinocchio$message__cachemiss$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$pinocchio$message__cachemiss$v1(void);
extern void __dtrace_probe$pinocchio$threaded$v1$63686172202a(char *);
extern int __dtrace_isenabled$pinocchio$threaded$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
