#ifndef PINOCCHIO_LIB_SHELL_READLINE_PDOUBLELINKEDLIST
#define PINOCCHIO_LIB_SHELL_READLINE_PDOUBLELINKEDLIST 

#include <pinocchio.h>
extern void init_Shell_ReadLine_PDoubleLinkedList_methods();

extern void init_Shell_ReadLine_PDoubleLinkedList_layout();

#include <lib/lib.h>

extern Optr layout_Shell_ReadLine_DoubleLinkedList_Class_class;
extern Optr slot_Shell_ReadLine_DoubleLinkedList_size;
extern Optr slot_Shell_ReadLine_DoubleLinkedList_start;
extern Optr slot_Shell_ReadLine_DoubleLinkedList_end;
extern Optr slot_Shell_ReadLine_DoubleLinkedList_current;
extern Optr slot_Shell_ReadLine_DoubleLinkedList_position;
extern Optr layout_Shell_ReadLine_DoubleLinkedList;


#endif //PINOCCHIO_LIB_SHELL_READLINE_PDOUBLELINKEDLIST